---
- hosts: localhost
  vars:
    apt_packages:
      - name: aisleriot
        state: absent
      #- name: chrome-gnome-shell
      - name: gawk
      - name: gnome-mahjongg
        state: absent
      - name: gnome-mines
        state: absent
      #- name: gnome-shell-extension-prefs
      - name: gnome-sudoku
        state: absent
      - name: gnome-sushi
        state: absent
      - name: gnome-todo-common
        state: absent
      - name: gnome-todo
        state: absent
      - name: gnome-tour
        state: absent
      - name: htop
      - name: jq
      - name: libgnome-games-support-1-3
        state: absent
      - name: libgnome-games-support-common
        state: absent
      - name: quadrapassel
        state: absent
      - name: rhythmbox
        state: absent
      - name: vgrabbj
      - name: uvccapture
      - name: stopmotion
      - name: zorin-connect
      - name: gnome-shell-extension-zorin-connect
      - name: chrome-gnome-shell # newer name: gnome-browser-connector
      - name: gnome-shell-extension-prefs
      - name: gnome-shell-extension-manager
      - name: motion
        state: absent
      - name: ffmpeg
      - name: podman
      - name: libwebkit2gtk-4.1-dev
      - name: build-essential
      - name: curl
      - name: wget
      - name: file
      - name: libxdo-dev
      - name: libssl-dev
      - name: libayatana-appindicator3-dev
      - name: librsvg2-dev
      # postgresql https://www.postgresql.org/download/linux/ubuntu/
    apt_repositories:
     - sources_entry: ppa:giuspen/ppa
    #  - sources_entry: ppa:ubuntu-toolchain-r/test
    asdf_user: "{{ lookup('env', 'USER') }}"
    asdf_group: "{{ lookup('env', 'USER') }}"
    asdf_plugins:
      - name: nodejs
        versions:
          - 18.4.0
          - 16.16.0
        # global:
      - name: pnpm
        versions:
          - 8.15.4
      - name: python
      - name: ruby
      - name: packer
      - name: terraform
      - name: terraform-ls
    dotfiles:
      - repo: "https://github.com/mat-green/dotfiles.git"
        branch: zorin
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles/mat-green"
    flatpak_apps:
      - name: com.adobe.Reader
      - name: com.discordapp.Discord
      - name: com.google.Chrome
      - name: com.jgraph.drawio.desktop
      - name: com.leinardi.gwe
        autostart: yes
      - name: com.slack.Slack
      - name: com.spotify.Client
      - name: com.system76.Popsicle
      - name: com.usebottles.bottles
      - name: io.github.hakandundar34coding.system-monitoring-center
      - name: io.github.MakovWait.Godots
      - name: io.github.mimbrero.WhatsAppDesktop
      - name: io.github.trevorsandy.LPub3D
      - name: io.podman_desktop.PodmanDesktop
      - name: md.obsidian.Obsidian
      - name: org.blender.Blender
        cmd: blender
      - name: org.freecadweb.FreeCAD
      - name: org.leocad.LeoCAD
      - name: org.signal.Signal
      - name: org.telegram.desktop
      - name: us.zoom.Zoom
    python_packages: # global python libs
      - numpy
      - pyside2
    wine_apps:
      - name: Studio+2.0.exe # bricklink-studio
      - name: canon-captureontouch-utility # password
  roles:
  # System Set Up
    - name: bluetooth
    - name: dotfiles
    - name: oh-my-zsh
    # TODO: Setting Theme - complex set up using 'gsetting' command but is a simple gui change.
  # Software Install
    - name: flatpak
#    - name: snap
    - name: wine
    - name: apt
    - name: pip
    - name: os-tweaks
  # Development Software
    - name: git
    - name: cimon-io.asdf
    - name: vscode
    - name: doctl
    - name: godot-conf
    - name: rust
    # TODO: Gnome extensions https://linuxconfig.org/how-to-install-gnome-shell-extensions-from-zip-file-using-command-line-on-ubuntu-18-04-bionic-beaver-linux
