# [START] Git Configuration ---------------------------------------------------
- name: Git Email Configuration
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ lookup('env', 'GIT_USER_EMAIL') }}"
  when: lookup('env', 'GIT_USER_EMAIL')

- name: Git Email Configuration
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ lookup('env', 'GIT_USER_NAME') }}"
  when: lookup('env', 'GIT_USER_NAME')
# [END]   Git Configuration ---------------------------------------------------

# [START] Mac OSX Configuration -----------------------------------------------
- name: Allow execution access
  ansible.builtin.command: xattr -d -r com.apple.quarantine {{ item }}
  with_items: "{{ allowed_executables }}"

- name: Apply domain defaults
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type | default(omit) }}"
    state: present
  with_items:
    - domain: "com.apple.dock"
      key: "autohide"
      value: true
      type: bool
    - domain: "com.apple.dock"
      key: "largesize"
      value: 128.0
      type: float
    - domain: "com.apple.dock"
      key: "magnification"
      value: true
      type: bool
    - domain: "com.apple.dock"
      key: "mineffect"
      value: "genie"
# [END]   Mac OSX Configuration -----------------------------------------------
