# [START] Git Configuration ---------------------------------------------------
- name: Git Email Configuration
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ lookup('env', 'GIT_USER_EMAIL') }}"
  when: lookup('env', 'GIT_USER_EMAIL')

- name: Git Email Configuration
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ lookup('env', 'GIT_USER_NAME') }}"
  when: lookup('env', 'GIT_USER_NAME')
# [END]   Git Configuration ---------------------------------------------------

# [START] Mac OSX Configuration -----------------------------------------------
- name: Allow execution access
  ansible.builtin.command: xattr -d -r com.apple.quarantine {{ item }}
  with_items: "{{ allowed_executables }}"


# [END]   Mac OSX Configuration -----------------------------------------------
